export const DETAIL_DATA = 'DETAIL_DATA'
export const LIKE = 'LIKE'
export const COLLECT = 'COLLECT'
export const LOVELIST = 'LOVELIST'
export const LOVEMASK = 'LOVEMASK'
export const GUANZHU = 'GUANZHU'
export const LOGIN_DATA = 'LOGIN_DATA'